---
site_name: "Automation Primer for Network Engineers"
site_description: Intorduction to tools and processes used in network automation
nav:
  - WSL with VS Code: "wsl_vscode.md"


repo_url: https://github.com/joshgilby/automationprimer
repo_name: joshgilby/automationprimer

theme: jeckyll-theme-slate