---
site_name: "Automation Primer for Network Engineers"
site_description: Intorduction to tools and processes used in network automation
nav:
  - FAQ: "index.md"
  - Agenda: "agenda.md"
  - WSL with VS Code: "wsl_vscode.md"
  - Optional:
    - NAPALM Mock: napalm_mock.md
    - rich SVG: rich_svg.md
    - Pydantic: pydantic_plus.md
    - Testing Typer: testing_typer.md
    - Publish Package: publish_package.md



repo_url: https://github.com/joshgilby/automationprimer
repo_name: joshgilby/automationprimer

theme:
  name: Slate
  palette:
    - scheme: slate
  features:
    - navigation.tracking

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
